### ISSUE TITLE
Clarifying Transferable MediaStreamTrack Types

### ISSUE THREAD

**Issue by bc-lee** [w3c/mediacapture-extensions#154]
It's promising to see support for transferring `MediaStreamTrack` to Web Workers in the latest Safari Technology Preview 196 and Safari Beta 18. I successfully built a demo that utilizes transferred `MediaStreamTrack` as input for `MediaStreamTrackProcessor` and `VideoTrackGenerator`.

However, Chromium Canary's implementation under the `MediaStreamTrackTransfer` flag seems to have limitations. Attempting to transfer a `MediaStreamTrack` obtained from getUserMedia (gUM) within the window context to a Web Worker results in this error:

```
DataCloneError: Failed to execute 'postMessage' on 'Worker': MediaStreamTrack could not be serialized.
```

This suggests that certain `MediaStreamTrack` types might not be transferable due to various reasons. Unfortunately, I couldn't find any definitive information about transferable `MediaStreamTrack` types until diving into Chromium's source code (specifically, the `IsMediaStreamDeviceTransferrable` function within [media_stream_request.cc](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/common/mediastream/media_stream_request.cc;drc=7d13c5bf7fee2e5b3e4f25b4b836daea10a01932)).

Establishing a clear consensus on which `MediaStreamTrack` types are transferable, followed by documentation within the specification, would be beneficial for web developers.

**Comment by youennf** [comment]
I think all MediaStreamTrack(s) are expected to be transferable (except [CanvasCaptureMediaStreamTrack](https://www.w3.org/TR/mediacapture-fromelement/#dom-canvascapturemediastreamtrack) since it is not exposed in DedicatedWorker).

AFAIK, Chrome is not implementing yet MediaStreamTrack transfer to DedicatedWorker.
See for instance https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/modules/mediastream/media_stream_track.idl.
Filing a bugs on chromium bug tracker might be the best approach.

**Comment by aboba** [comment]
Closing - not a spec issue.
