### ISSUE TITLE
In-content device selection a mistake. Too complicated, leaks info

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-extensions#2]
In hindsight, in-content device selection was a mistake. It's
 * **Too permissive**—assumes all devices granted up-front to work effectively (wo/reprompt)
 * **Too complicated**—having every site write a decent picker compatibly has been a failure:
    * Exhibit A: Changing camera **_or_** mic in [webrtc samples](https://webrtc.github.io/samples/src/content/devices/input-output/) re-prompts **_both_** in Firefox; flickers
    * Mobile devices typically can't open more than once device at a time ("stop-then-pick")
    * Stop-then-pick is an inferior user experience on desktops
    * Dealing with different browser permission models severely limits design (no previews)
 * **Leaks private info**—fails PING review https://github.com/w3c/mediacapture-main/issues/640
 * **Too limiting**—no path to privacy (can't avoid redundant re-prompts *after* user selection)

The PING outlines the way forward in https://github.com/w3c/mediacapture-main/issues/640#issuecomment-549540203:
> Privacy-by-default flow:
> 
> Initially site has access to no devices or device labels
> 
> 1. site asks for category (or categories) of device
> 2. browser prompts user for one, many or all devices
> 3. site gains access to only the device, and device label, of the hardware the user selects.

That's an in-chrome picker (_"in-chrome"_ = implemented in the browser). In-chrome pickers
 * **Are proven successful**—in [getDisplayMedia](https://jan-ivar.github.io/dummy/gdm.html)
 * **The way forward**—for speakers https://github.com/w3c/mediacapture-output/pull/86
 * **Remove the need to grant all devices** ❤️ 
 * **Let UAs solve mobile** platforms that can’t open multiple devices (mute temporarily)
 * **Let UAs solve camera previews** maybe even in a (non-creepy) Brady Bunch grid!

~https://github.com/w3c/mediacapture-main/pull/644 is my proposal for reshaping `getUserMedia` to serve this need, as well as solve https://github.com/w3c/mediacapture-main/issues/648.~

**Comment by bradisbell** [comment]
Removing device labels is damaging to usability for anyone using multiple sound devices.  It is critical for the application to show to the user what inputs/outputs correlate to which physical devices.

Suppose I have a typical audio mixer application with 8 inputs.  The user shares these devices with the application.  What are we to display in the UI?  "Microphone 1", "Microphone 2", "Microphone 3"... we don't even know that they're microphones.  At least with device labels, I can say "Line In 1/2", "Logitech Camera L/R".  Otherwise, the user has no way of really seeing what goes to what.  If a user gives permission to a device, they should be able to fully utilize that device with the web application, which includes seeing what device it is.

I think a way to solve the privacy concern is to hide the label for a "default" device, while still providing useful labels when specific devices are chosen.

This is an example of some recent privacy-related decisions that have significantly damaged the usefulness of web-based media applications.  I'd urge everyone making these decisions to consider the broader uses of these APIs, beyond video calling.  I think that privacy concerns can be adequately addressed while still empowering users to use their own hardware on the web.

**Comment by jan-ivar** [comment]
> Suppose I have a typical audio mixer application with 8 inputs. The user shares these devices with the application. What are we to display in the UI?

@bradisbell Thanks for bringing up this example, as multi-device use is a supported, if still emerging, use case. This [spec](https://w3c.github.io/mediacapture-extensions/#web%20compatibility) (so far) only deprecates `deviceInfo.label` not `track.label` for this reason. Sites retain access to labels of devices that are live.

So this issue didn't get rid of labels entirely, which has its problems, but we're tackling those in separate issues like https://github.com/w3c/mediacapture-main/issues/747 and  https://github.com/w3c/mediacapture-extensions/issues/1. Hope that helps clarify.

**Comment by bradisbell** [comment]
@jan-ivar Thank you for that clarification!  I've done some testing, and I think that keeping the track label solves the issue for my use case.
